### ISSUE TITLE
🐛 [Bug] https://ocelot.social/ is throwing a 404 error

### ISSUE THREAD

**Issue by strypey** [Ocelot-Social-Community/ocelot.social#2]
https://ocelot.social/ is throwing a 404 error.

![screenshot-ocelot_social-2023-11-15-22-17-06](https://github.com/Ocelot-Social-Community/ocelot.social/assets/313316/03f9abc4-558e-4f24-b8c9-5f9c8bc9fdbd)

Error message;

"There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account."

**Comment by mahula** [comment]
Thany you, @strypey.
This has been taken care of.
